### ISSUE TITLE
Authentication.

### ISSUE THREAD

**Issue by kobbyopoku** [QueBaseTech/pharmacy-pos#15]
I am stuck at the login.  I need username and password

**Comment by nyugoh** [comment]
How have you installed the app?

**Comment by kobbyopoku** [comment]
![2019-05-07 (7)](https://user-images.githubusercontent.com/10862896/57313131-79cc6600-70de-11e9-9efc-0eee190d5c6c.png)

This is where i got stuck. I dont know if i missed come steps

**Comment by nyugoh** [comment]
Hi @kobbyopoku  did you manage to fix the issue?

**Comment by AhmedMASalam** [comment]
Hi nyugoh,
login issue, Credential I used for login: un:"root", pw:""
![Capture](https://user-images.githubusercontent.com/49006773/73617277-f7051700-462d-11ea-968a-847f89a0d1f4.PNG)

**Comment by AhmedMASalam** [comment]
> Hi nyugoh,
> login issue, Credential I used for login: un:"root", pw:""
> ![Capture](https://user-images.githubusercontent.com/49006773/73617277-f7051700-462d-11ea-968a-847f89a0d1f4.PNG)

Also, admin, admin

**Comment by nyugoh** [comment]
@AhmedMASalam Copy the file `.dbconfig.json` found inside `mariadb` folder to `library/wpos/`
Also copy the contentst of `docs-template` to a new folder `docs`

**Comment by AhmedMASalam** [comment]
> @AhmedMASalam Copy the file `.dbconfig.json` found inside `mariadb` folder to `library/wpos/`
> Also copy the contentst of `docs-template` to a new folder `docs`

I copied the files, but still the same issue there.

**Comment by nyugoh** [comment]
Check if you have the following:-

- [ ] Have you updated .dbconfig.json with the correct database credentials
- [ ] Open localhost/<`installation-folder`>/install, This will create all the tables necessary in you database

**Comment by AhmedMASalam** [comment]
Thanks nyugoh it works now.

**Comment by nyugoh** [comment]
@AhmedMASalam Welcome
